/** Đường dẫn type-safe. Slug là dữ liệu — chỉ khai báo builder ở đây. */
export const routes = {
  home: "/",
  about: "/gioi-thieu",
  workshop: "/gioi-thieu/xuong-san-xuat",
  process: "/gioi-thieu/quy-trinh",
  services: "/dich-vu",
  service: (slug: string) => `/dich-vu/${slug}`,
  products: "/san-pham",
  productCategory: (cat: string) => `/san-pham/${cat}`,
  product: (cat: string, slug: string) => `/san-pham/${cat}/${slug}`,
  solutions: "/giai-phap",
  solution: (slug: string) => `/giai-phap/${slug}`,
  projects: "/du-an",
  project: (slug: string) => `/du-an/${slug}`,
  locations: "/khu-vuc",
  location: (p: string) => `/khu-vuc/${p}`,
  locationService: (p: string, s: string) => `/khu-vuc/${p}/${s}`,
  pricing: "/bang-gia",
  quote: "/bao-gia",
  quoteThanks: "/bao-gia/thanh-cong",
  blog: "/blog",
  post: (slug: string) => `/blog/${slug}`,
  faq: "/cau-hoi-thuong-gap",
  contact: "/lien-he",
  warranty: "/chinh-sach-bao-hanh",
  privacy: "/chinh-sach-bao-mat",
} as const;
